# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: baseline.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'baseline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61seline.proto\x12\x06hermes\"\x8e\x01\n\rAgentEnvelope\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12\x0f\n\x07span_id\x18\x06 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x07 \x01(\x03\"\x8d\x01\n\x0b\x41gentResult\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x10\n\x08\x62ytes_in\x18\x04 \x01(\x03\x12\x11\n\tbytes_out\x18\x05 \x01(\x03\x12\x17\n\x0fmessage_path_ms\x18\x06 \x01(\x03\x12\r\n\x05\x65rror\x18\x07 \x01(\t\"u\n\x0bPlanRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04repo\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\x11\n\ttest_name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0c\n\x04seed\x18\x06 \x01(\x05\"C\n\x0cPlanResponse\x12\r\n\x05steps\x18\x01 \x03(\t\x12\x10\n\x08\x61pproach\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x05\"S\n\x0b\x43odeRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x12\n\nplan_steps\x18\x03 \x03(\t\x12\x0c\n\x04seed\x18\x04 \x01(\x05\"`\n\x0c\x43odeResponse\x12\r\n\x05patch\x18\x01 \x01(\t\x12\x15\n\rfiles_changed\x18\x02 \x03(\t\x12\x13\n\x0blines_added\x18\x03 \x01(\x05\x12\x15\n\rlines_removed\x18\x04 \x01(\x05\"N\n\x0bTestRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttest_name\x18\x02 \x01(\t\x12\r\n\x05patch\x18\x03 \x01(\t\x12\x0c\n\x04seed\x18\x04 \x01(\x05\"U\n\x0cTestResponse\x12\x0e\n\x06passed\x18\x01 \x01(\x08\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\x12\x10\n\x08\x66\x61ilures\x18\x04 \x03(\t2B\n\nArmService\x12\x34\n\x06Handle\x12\x15.hermes.AgentEnvelope\x1a\x13.hermes.AgentResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'baseline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTENVELOPE']._serialized_start=27
  _globals['_AGENTENVELOPE']._serialized_end=169
  _globals['_AGENTRESULT']._serialized_start=172
  _globals['_AGENTRESULT']._serialized_end=313
  _globals['_PLANREQUEST']._serialized_start=315
  _globals['_PLANREQUEST']._serialized_end=432
  _globals['_PLANRESPONSE']._serialized_start=434
  _globals['_PLANRESPONSE']._serialized_end=501
  _globals['_CODEREQUEST']._serialized_start=503
  _globals['_CODEREQUEST']._serialized_end=586
  _globals['_CODERESPONSE']._serialized_start=588
  _globals['_CODERESPONSE']._serialized_end=684
  _globals['_TESTREQUEST']._serialized_start=686
  _globals['_TESTREQUEST']._serialized_end=764
  _globals['_TESTRESPONSE']._serialized_start=766
  _globals['_TESTRESPONSE']._serialized_end=851
  _globals['_ARMSERVICE']._serialized_start=853
  _globals['_ARMSERVICE']._serialized_end=919
# @@protoc_insertion_point(module_scope)
