name: Ban tracked artifacts
on: [pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fail on tracked artifacts
        run: |
          set -euo pipefail
          banned=$(git ls-files | grep -E '^(runs/|data/|\.hf/|\.mirrors/|scratch/)' || true)
          if [ -n "$banned" ]; then
            echo "❌ Tracked artifacts found:"
            echo "$banned"
            exit 1
          fi
          echo "✅ No tracked artifacts found"
      
      - name: Ban toy/smoke in source (not tests/docs)
        run: |
          offenders=$(find . -type f \( -name "*.py" -o -name "*.sh" -o -name "*.yaml" -o -name "*.yml" \) ! -path "./tests/*" ! -path "./docs/*" -exec grep -nH '\b\(smoke\|toy\)_\?[0-9]*\b' {} \; 2>/dev/null || true)
          if [ -n "$offenders" ]; then
            echo "❌ Toy/Smoke patterns in source:"
            echo "$offenders"
            exit 1
          fi
          echo "✅ No toy/smoke patterns in source"
      
      - name: Check for demo files
        run: |
          echo "Checking for synthetic demo files..."
          demos=$(git ls-files | grep -E 'demo_.*\.py$' | grep -v '^tests/' || true)
          if [ -n "$demos" ]; then
            echo "::error ::Repository contains demo files outside tests/:"
            echo "$demos"
            exit 1
          fi
          echo "✅ No demo files found outside tests/"