name: Ban tracked artifacts

on: [pull_request]

jobs:
  ban-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for tracked artifacts
        run: |
          set -e
          bad=$(git ls-files | egrep '^(runs|data|\.hf|\.mirrors|scratch)/' || true)
          if [ -n "$bad" ]; then
            echo "::error ::Repository contains tracked artifacts:"
            echo "$bad"
            exit 1
          fi