name: Ban Toy Datasets

on:
  push:
    branches: [ main, sujinesh/* ]
  pull_request:
    branches: [ main ]

jobs:
  check-toy-datasets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for banned toy/smoke/mock patterns
      run: |
        echo "Checking for banned toy/smoke/mock patterns..."
        
        # Check for toy dataset references (excluding unittest.mock and docs)
        if grep -r -E "(toy_tasks|--toy|smoke_test|--smoke)" . \
          --exclude-dir=.git \
          --exclude-dir=__pycache__ \
          --exclude-dir=docs \
          --exclude-dir=tests \
          --exclude-dir=.claude \
          --exclude-dir=.pytest_cache \
          --exclude="*.parquet" \
          --exclude="*.pyc" \
          --exclude="*.md" \
          --exclude="*.log" \
          2>/dev/null | grep -v "^[[:space:]]*#"; then
          echo "ERROR: Found banned toy/smoke patterns in source code"
          exit 1
        fi
        
        # Check for vendored dataset content
        if [ -d "data/swebench_lite/" ]; then
          echo "ERROR: Found vendored dataset content in data/swebench_lite/"
          exit 1
        fi
        
        # Ensure no synthetic payload generators
        if grep -r "def.*generate.*synthetic\|fake.*pytest\|manufactured.*output" agents/ 2>/dev/null; then
          echo "ERROR: Found synthetic data generation in agents"
          exit 1
        fi
        
        echo "✅ No banned patterns found"