name: Ban tracked artifacts

on: [pull_request]

jobs:
  ban-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for tracked artifacts
        run: |
          set -e
          bad=$(git ls-files | egrep '^(runs|data|\.hf|\.mirrors|scratch)/' || true)
          if [ -n "$bad" ]; then
            echo "::error ::Repository contains tracked artifacts:"
            echo "$bad"
            exit 1
          fi
      
      - name: Check for demo files
        run: |
          set -e
          demos=$(git ls-files | egrep '(demo_.*\.py|.*_minimal.*\.py)' | grep -v '^tests/' || true)
          if [ -n "$demos" ]; then
            echo "::error ::Repository contains demo/minimal files outside tests:"
            echo "$demos"
            exit 1
          fi