name: ci
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: Lint
        run: make lint
      - name: Test (emit evidence)
        run: ARTIFACTS_DIR=artifacts/M0 make test
      - name: Upload artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/**
          if-no-files-found: ignore